services:
  webapp:
    build:
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    environment:
      - NODE_ENV=production
    networks:
      - documento-network
    restart: unless-stopped

networks:
  documento-network:
    driver: bridge
